package com.sunnychung.application.multiplatform.hellohttp.ux

enum class TestTag {
    ContainerView,
    DialogContainerView,
    DialogCloseButton,
    ProjectNameAndSubprojectNameDialogTextField,
    ProjectNameAndSubprojectNameDialogDoneButton,
    FirstTimeCreateProjectButton,
    FirstTimeCreateSubprojectButton,
    EditEnvironmentsButton,
    EnvironmentDialogCreateButton,
    EnvironmentDialogEnvNameTextField,
    EnvironmentEditorTab,
    EnvironmentEditorVariableTabContent,
    EnvironmentEditorSslTabContent,
    CreateRequestOrFolderButton,
    RequestUrlTextField,
    RequestFetchApiSpecButton,
    RequestCancelFetchApiSpecButton,
    RequestParameterTypeTabContainer,
    RequestParameterTypeTab,
    RequestStringBodyTextField,
    RequestGraphqlDocumentTextField,
    RequestGraphqlVariablesTextField,
    RequestPreFlightTabContent,
    RequestPreFlightScriptTextField,
    RequestFireOrDisconnectButton,
    RequestSendPayloadButton,
    RequestCompleteStreamButton,
    RequestAddPayloadExampleButton,
    RequestPayloadTextField,
    ResponseStatus,
    ResponseDuration,
    ResponseBody,
    ResponseError,
    ResponseBodyEmpty,
    ResponseStreamLog,
    ResponseStreamLogItemTime,
}

enum class TestTagPart {
    RequestMethodDropdown,
    RequestHeader,
    RequestQueryParameter,
    RequestBodyTypeDropdown,
    RequestBodyFormUrlEncodedForm,
    RequestBodyMultipartForm,
    RequestBodyFileForm,
    RequestGraphqlOperationName,
    RequestApiSpecDropdown,
    RequestGrpcServiceDropdown,
    RequestGrpcMethodDropdown,
    ExampleVariable,
    PreflightUpdateEnvByHeader,
    PreflightUpdateEnvByQueryParameter,
    PreflightUpdateEnvByBody,
    PreflightUpdateEnvByGraphqlVariables,
    EnvironmentDropdown,
    EnvironmentEditorVariableKeyValue,
    EnvironmentHttpProtocolVersionDropdown,
    EnvironmentSslTrustedServerCertificates,
    EnvironmentSslClientCertificates,
    EnvironmentDisableSystemCaCertificates,
    ClientCertificate,
    PrivateKey,
    Bundle,
    CreateButton,
    ListItemLabel,
    Inherited,
    InheritedFromEnvironment,
    Current,
    Key,
    Value,
    FileButton,
    ValueTypeDropdown,
    DropdownButton,
    DropdownMenu,
    DropdownItem,
    DropdownLabel,
}

fun buildTestTag(vararg parts: Any?): String? {
    if (parts.any { it == null }) {
        return null
    }
    return parts.joinToString("/")
}
