name: Debug Verification Tests
on:
  push:
    branches:
      - '**'
jobs:
  test:
    strategy:
      matrix:
        # macos-13 for Intel Mac, macos-14 for Apple Chips Mac
        os: [ubuntu-20.04, windows-2019, windows-2022, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - run: |
          export GRADLE_OPTS='-Xmx64m -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx3072m -XX:+HeapDumpOnOutOfMemoryError"'
          ./gradlew jvmTest --tests 'com.sunnychung.application.multiplatform.hellohttp.test.util.ChunkedLatestFlowTest'
        shell: bash # let Windows use bash
      - uses: actions/upload-artifact@v4
        with:
          name: ux-test-result_${{ matrix.os }}
          path: ux-and-transport-test/build/reports/tests/test
        if: ${{ always() }}
      - uses: actions/upload-artifact@v4
        with:
          name: unit-test-result_${{ matrix.os }}
          path: build/reports/tests
        if: ${{ always() }}
      - uses: actions/upload-artifact@v4
        with:
          name: ux-test-error_${{ matrix.os }}
          path: ux-and-transport-test/test-error-screenshot
        if: ${{ always() }}
